name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
    - uses: actions/checkout@v3

    - name: make
      run: make
      
    - name: make re
      run: make re
      
    - name: make fclean
      run: make fclean
